import fonts from '@/libs/ui/core/fonts';
import './globals.css';
import type { Metadata } from 'next';
import Text from '@/libs/ui/components/text';
import Card from '@/libs/ui/components/card';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`dark ${fonts.className}`}></body>
    </html>
  );
}
